# Copyright 2026 The WheelOS Team. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Created Date: 2026-03-03
# Author: daohu527


from ultralytics import YOLO
import os


def start_train():
    # 1. Load model
    model = YOLO('yolo12n.pt')

    # 2. Start training
    # The `data` parameter should point to the absolute path of the data.yaml generated by this repo
    results = model.train(
        data=os.path.abspath('./YOLO_Dataset/data.yaml'),
        epochs=100,         # number of training epochs
        imgsz=640,          # input image size
        batch=16,           # batch size; reduce to 8 or 4 if GPU memory is limited
        device=0,           # GPU device index or 'cpu' for CPU training
        workers=8,          # number of data loader workers
        project='my_yolo_project',  # project name to save results
        name='exp1'         # experiment name
    )


if __name__ == "__main__":
    start_train()
